name: exam_practice_app
description: "Exam practice Apps."
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localization:
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  page_flip: ^0.2.5+1
  get: ^4.7.2
  # flutter_localization: ^0.3.3
  font_awesome_flutter: ^10.9.0
  provider: ^6.1.5
  motion_tab_bar:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
flutter_inte: enabled:true
